### ISSUE TITLE
what is usage of constant queue in the Monitorable class

### ISSUE THREAD

**Issue by dylanGao** [kyotaw/exchangeEx#1]
hi，i cannot knew the usage of  queue in the Monitorable class.
It was implemented in the class:
    let queue: DispatchQueue!

can you help me ?

**Comment by kyotaw** [comment]
Hi dylanGao,
Actually, Monitorable.queue is not used. In the first version,  Monitorable was implemented using queue, and now it has been replaced with Timer. So Monitorable.queue is garbage code and should be removed. Thank you for pointing out the issue!
